accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name='accounts'

urlpatterns=[
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

book/urls.py
from django.urls import path
from . import views


urlpatterns=[
    path('', views.index_view, name='index'),
    path('book/',views.ListBookView.as_view(), name='list_book'),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name='detail_book'),
    path('book/create/', views.CreateBookView.as_view(), name='create_book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete_book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update_book'),
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review'),
]

bookproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('book.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models

from .consts import MAX_RATE
from cloudinary.models import CloudinaryField 

RATE_CHOICES = [(x, str(x)) for x in range(0, MAX_RATE + 1)]

CATEGORY=(('ビジネス', 'ビジネス'), ('生活', '生活'), ('R-18', 'R-18'), ('その他', 'その他'))

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    title=models.CharField(max_length=100)
    author=models.CharField(max_length=100, null=True, blank=True)
    text=models.TextField()
    thumbnail=CloudinaryField('image', null=True, blank=True)
    category=models.CharField(
        max_length=100,
        choices=CATEGORY
    )
    user=models.ForeignKey('auth.User', on_delete=models.CASCADE)

    tags = models.ManyToManyField('Tag', blank=True, related_name="books")
    
    def __str__(self):
        return self.title

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    def __str__(self):
        return self.title
# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',)

book/forms.py
from django import forms
from .models import Book, Tag

class BookForm(forms.ModelForm):
    new_tags = forms.CharField(
        required=False,
        help_text='カンマ区切りで新しいタグを入力できます'
    )

    class Meta:
        model = Book
        fields = ('title', 'author', 'text', 'category', 'thumbnail', 'tags')
    
    def save(self, commit=True):
        book = super().save(commit=False)
        if commit:
            book.save()
            self.save_m2m()
            #新しいタグの処理
            new_tags = self.cleaned_data.get('new_tags', '')
            if new_tags:
                for name in [t.strip() for t in new_tags.split(',') if t.strip()]:
                    tag, created = Tag.objects.get_or_create(name=name)
                    book.tags.add(tag)
        return book

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm

class SignupView(CreateView):
    model = User
    form_class = SignupForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('index')

# Create your views here.

book/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Avg
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .consts import ITEM_PER_PAGE
from .models import Book, Review
from django.conf import settings
from .forms import BookForm

class ListBookView(LoginRequiredMixin, ListView):
    template_name='book/book_list.html'
    model=Book
    paginate_by=ITEM_PER_PAGE

    def get_queryset(self):
        qs = Book.objects.all()

        #カテゴリーで絞り込み
        category = self.request.GET.get('category')
        self.category = self.request.GET.get('category')
        self.sort = self.request.GET.get('sort')

        if category:
            qs = qs.filter(category=category)

        #ソート順
        sort = self.request.GET.get('sort')
        if sort == 'rating':
            qs = qs.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')
        else:  #デフォルトは新着順
            qs = qs.order_by('-id')
        
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['sort'] = self.sort
        return context        
    
class DetailBookView(LoginRequiredMixin, DetailView):
    template_name='book/book_detail.html'
    model=Book

class CreateBookView(LoginRequiredMixin, CreateView):
    template_name='book/book_create.html'
    model=Book
    success_url=reverse_lazy('list_book')
    form_class = BookForm

    def form_valid(self, form):
        form.instance.user = self.request.user  # ログイン中ユーザーをセット
        return super().form_valid(form)
        

class DeleteBookView(LoginRequiredMixin, DeleteView):
    template_name='book/book_confirm_delete.html'
    model=Book
    success_url=reverse_lazy('list_book')

    def get_object(self, queryset=None):
        obj=super().get_object(queryset)

        if obj.user !=self.request.user:
            raise PermissionDenied
        
        return obj

class UpdateBookView(LoginRequiredMixin, UpdateView):
    template_name='book/book_update.html'
    model=Book
    form_class = BookForm

    def get_object(self, queryset=None):
        obj=super().get_object(queryset)

        if obj.user !=self.request.user:
            raise PermissionDenied
        
        return obj
    
    def get_success_url(self):
        return reverse('detail_book', kwargs={'pk': self.object.id})

def index_view(request):
    object_list=Book.objects.order_by('-id')  #新着順
    ranking_list=Book.objects.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')

    paginator=Paginator(ranking_list, ITEM_PER_PAGE)
    page_number=request.GET.get('page',1)
    page_obj=paginator.page(page_number)

    return render(
        request,
        'book/index.html',
        {'object_list': object_list, 'ranking_list': ranking_list, 'page_obj':page_obj}
    )

class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    fields = ('book', 'title', 'text', 'rate')
    template_name = 'book/review_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Book.objects.get(pk=self.kwargs['book_id'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.book = Book.objects.get(pk=self.kwargs['book_id'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail_book', kwargs={'pk': self.object.book.id})

# Create your views here.

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}
{% block content %}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        <input type="text" name="username" class="form-control my-4" placeholder="ユーザー ID">
        <input type="text" name="password1" class="form-control mt-4" placeholder="パスワード">
        <input type="text" name="password2" class="form-control mt-4" placeholder="パスワード確認用">
        <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください。</small>
        {% if form.errors %}
        <div class="text-danger">
            {% for field in form %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <p>{{ error }}</p>
            {% endfor %}
        </div>
        {% endif %}
        <button type="submit" class="btn btn-success m-2">アカウント作成</button>
    </form>
{% endblock %}

book/templates/book/book_confirm_delete.html
{% extends 'base.html' %}

{% block title %}書籍削除{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <button type="submit">{{object.title}}を削除する</button>
    </form>
{% endblock %}

book/templates/book/book_create.html
{% extends 'base.html' %}

{% block title %}書籍作成{% endblock %}

{% block content %}
    <form method="POST" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">{% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="作成する">
    </form>
{% endblock content %}

book/templates/book/book_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.title }}{% endblock %}
{% block h1 %}書籍詳細{% endblock %}
{% block content %}
  <div class="p-4 m-4 bg-light border border-success rounded">
      <h2 class="text-success">{{ object.title }}</h2>
      <h5 class="text-muted">作者 : {{ object.author }}</h5>
        <p>{{ object.text }}</p>
        <div class="border p-4 mb-2">
          {% for review in object.review_set.all %}
          <div>
            <h3 class="h4">{{ review.title }}</h3>
            <div class="px-2">
              <span>(投稿ユーザー: {{ review.user.username }})</span>
              <h6>評価: {{ review.rate }}点</h6>
              <p>{{  review.text}}</p>
            </div>
          </div>
          {% endfor %}
        </div>
        <a href="{% url 'list_book' %}" class="btn btn-primary">一覧へ</a>
        <a href="{% url 'review' object.pk %}" class="btn btn-primary">レビューする</a>
        <a href="{% url 'update_book' object.pk %}" class="btn btn-primary">編集する</a>
        <a href="{% url 'delete_book' object.pk %}" class="btn btn-primary">削除する</a>
        <h6 class="card-title">{{object.category}}</h6>
      </div>
  </div>
{% endblock content %}

book/templates/book/book_list.html
{% extends 'base.html' %}

{% block title %}書籍一覧{% endblock %}
{% block h1 %}書籍一覧{% endblock %}

{% block content %}
<div class="row">
    <div class="col-9">
      <div class="d-flex justify-content-between align-items-center p-2 bg-light border rounded mb-3">
          <!-- 左：現在の状態表示 -->
          <div>
              並び順: 
              <strong>
                  {% if sort == 'rating' %}
                      評価順
                  {% else %}
                      新着順
                  {% endif %}
              </strong> |
              カテゴリ: 
              <strong>
                  {% if category == 'ビジネス' %}ビジネス
                  {% elif category == '生活' %}生活
                  {% elif category == 'R-18' %}R-18
                  {% elif category == 'その他' %}その他
                  {% else %}すべて
                  {% endif %}
              </strong>
          </div>

          <!-- 右：並び替えリンク -->
          <div>
              <a href="?sort=new{% if category %}&category={{ category }}{% endif %}" class="btn btn-sm btn-outline-primary">新着順</a>
              <a href="?sort=rating{% if category %}&category={{ category }}{% endif %}" class="btn btn-sm btn-outline-primary">評価順</a>
          </div>
      </div>
        <div class="row">
            {% for item in object_list %}
            <div class="col-12 mb-4">
                <div class="card h-100 shadow-sm">
                    <div class="row g-0">
                        <!-- 左：テキスト -->
                        <div class="col-7 p-2 d-flex flex-column">
                            <h2 class="text-success">{{ item.title }}</h2>
                            <h6>作者：{{ item.author }}</h6>       
                            <h6>カテゴリ : {{ item.category }}</h6>
                            <p><strong>タグ:</strong>
                              {% for tag in item.tags.all %}
                                <span class="badge bg-info">{{ tag.name }}</span>
                              {% empty %}
                                <span class="text-muted">なし</span>
                              {% endfor %}
                            </p>
                            <div class="mt-3">
                                <a href="{% url 'detail_book' item.pk %}">詳細へ</a>
                            </div>
                        </div>
                        <!-- 右：画像 -->
                         <div class="col-md-4 d-flex align-items-center justify-content-end">
                            {% if item.thumbnail %}
                                <img src="{{ item.thumbnail.url }}" class="img-thumbnail" style="width: 200px; height: auto;" />
                            {% else %}
                                <p>No Image</p>
                            {% endif %} 
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
  <!-- カテゴリ絞り込み -->
  <div class="col-3">
      <h5>カテゴリで絞り込み</h5>
      <ul class="list-unstyled">
          <li><a href="?{% if sort %}sort={{ sort }}&{% endif %}">すべて</a></li>
          <li><a href="?{% if sort %}sort={{ sort }}&{% endif %}category=ビジネス">ビジネス</a></li>
          <li><a href="?{% if sort %}sort={{ sort }}&{% endif %}category=生活">生活</a></li>
          <li><a href="?{% if sort %}sort={{ sort }}&{% endif %}category=R-18">R-18</a></li>
          <li><a href="?{% if sort %}sort={{ sort }}&{% endif %}category=その他">その他</a></li>
      </ul>
  </div>
</div>

  {% include 'book/components/pagination.html' %}
{% endblock content %}

book/templates/book/book_update.html
{% extends 'base.html' %}

{% block title %}書籍修正{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">修正する</button>
    </form>
{% endblock %}

book/templates/book/components/pagination.html
{% if page_obj.has_other_pages %}
    <ul class="list-unstyled bm-0 d-flex justify-content-between">
        {% if page_obj.has_previous %}
            <a href="?page={{ previous_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">前へ</a>
        {% else %}
            <li class="text-muted">&lt;&lt;前へ</li>
        {% endif %}
        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}{% if request.GET.category %}&category={{ request.GET.category }}{% endif %}">次へ</a>
        {% else %}
            <li class="text-muted">次へ&gt;&gt;</li>
        {% endif %}
    </ul>
{% endif %}

book/templates/book/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}本棚アプリ{% endblock %}
{% block h1 %}本棚アプリ{% endblock %}

{% block content %}
<div class="row">
    <div class="col-9">
        <div class="row">
            {% for item in object_list %}
            <div class="col-12 mb-4">
                <div class="card h-100 shadow-sm">
                    <div class="row g-0">
                        <!-- 左：テキスト -->
                        <div class="col-7 p-2 d-flex flex-column">
                            <h2 class="text-success">{{ item.title }}</h2>
                            <h6>作者：{{ item.author }}</h6>       
                            <h6>カテゴリ : {{ item.category }}</h6>
                            <div class="mt-3">
                                <a href="{% url 'detail_book' item.pk %}">詳細へ</a>
                            </div>
                        </div>
                        <!-- 右：画像 -->
                         <div class="col-md-4 d-flex align-items-center justify-content-end">
                            {% if item.thumbnail %}
                                <img src="{{ item.thumbnail.url }}" class="img-thumbnail" style="width: 200px; height: auto;" />
                            {% else %}
                                <p>No Image</p>
                            {% endif %} 
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- サイドバー：評価順 -->
    <div class="col-3">
        <h2>評価順TOP2</h2>
        {% for ranking_book in page_obj %}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h3 class="text-success h5">{{ ranking_book.title }}</h3>
                {% if ranking_book.thumbnail %}
                <img src="{{ ranking_book.thumbnail.url }}" class="img-thumbnail">
                {% else %}
                <img src="{% static 'path/to/default_image.jpg' %}" class="img-thumbnail">
                {% endif %}
                <h6>評価:{{ ranking_book.avg_rating|floatformat }}点</h6>
                <a href="{% url 'detail_book' ranking_book.id %}">詳細を見る</a>
            </div>
        {% endfor %}
        {% include 'book/components/pagination.html' %}
    </div>
</div>
{% endblock content %}

book/templates/book/review_form.html
{% extends 'base.html' %}

{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}
{% block content %}
    <form method="post" class="p-4 m-4 bg-ligth border border-success rounded form-group">
        {% csrf_token %}
        <label>
            対象書籍
        </label>
        <input class="form-control" value="{{ book.title }}" readonly>
        <label>
            タイトル
        </label>
        <input class="form-control" name="title">
        <label>
            本文
        </label>
        <textarea class="form-control" name="text" rows="3"></textarea>
        <label>
            星の数
        </label>
        <select class="form-control" name="rate">
            <option value="0">0 (最低)</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3(普通)</option>
            <option value="4">4</option>
            <option value="5">5(最高)</option>
        </select>
        <input type="hidden" name="book" value="{{ book.id }}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    </form>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}|本棚アプリ</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-dark bg-success sticky-top">
      <div class="navbar-nav d-flex flex-row">
      <a class="nav-link mx-3" href="{% url 'index' %}">ホーム</a>
      <a class="nav-link mx-3" href="{% url 'list_book' %}">書籍一覧</a>
      <a class="nav-link mx-3" href="{% url 'create_book' %}">書籍登録</a>
      </div>
      <div class="navber-nav d-flex flex-row">
        {% if request.user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post" class="mx-3">
              {% csrf_token %}
              <button type="submit" class="btn btn-link nav-link p-0" style="text-decoration:none;">
                  ログアウト
              </button>
          </form>
        {% else %}
          <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
          <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
        {% endif %}
      </div>
    </nav>
    <div class="p-4">
      <h1>{% block h1 %}{% endblock %}</h1>
      {% block content %}{% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>